### PR TITLE
Bugfix: fix a missed ~empty~ check in isSubsetOf

### PR DESCRIPTION
**Pull request by bakkot**

### CODE REVIEW

**Comment by ljharb** [comment]
What's some JS code that would trigger this bug?

**Comment by bakkot** [comment]
```js
let x = new Set('a', 'b');
let evil = {
  size: 3,
  has() {
    x.delete('b');
    x.add('c');
    return true;
  },
  *keys(){}
};
x.isSubsetOf(evil);
```
That ends up calling `evil.has` with argument `~empty~`, which is not an ES language value.

**Comment by ljharb** [comment]
gotcha, thanks, LGTM

**Review by michaelficarra — APPROVED** [review]
😆

**Pull request merged**
